export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';
export const SET_ALL_FILTERS_ACTIVE = 'SET_ALL_FILTERS_ACTIVE';
export const REMOVE_ALL_ACTIVE_FILTERS = 'REMOVE_ALL_ACTIVE_FILTERS';
